finished loops and flowcontrol
gunahusko/java-home-exercises pull request #2
Opened 2022-03-01 14:28 UTC by gunahusko

2022-03-07 00:03 UTC, NilsKula requested changes

2022-03-07 00:03 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Exercise10.java
> +    public static void NumberSquare() {
var būt private un metožu nosaukumi camelCase `numberSquare`
redzēju arī citās vietās, tur neatkārtošu

2022-03-07 00:03 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Exercise9.java
> +            int dice1 = (int) (Math.random() * range) + min;
izmanto Random.nextInt(), unnecessary complexity un no casting labāk izvairīties pēc iespējas

2022-03-07 00:03 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Exercise9.java
> +            if (sum == num) isEqualsNum = false;
formatting: curly brackets

2022-03-07 00:03 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Exercise8.java
> +            for (int j=1; j<=(num-i)*4; j++) {
būtu labi nodefinēt 4/8 kā konstantes šajā gadijumā

2022-03-07 00:03 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Exercise7.java
> +        } else if (answer.equals("y")) {
šos noteikti tad varētu labāk apvienot vienā if statment ar `||`

2022-03-07 00:03 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Exercise5.java
> +        int dotLength = 30 - firstWord.length() - secondWord.length();
būtu arī te labi to 30 nodefinēt atsevišķi

2022-03-07 00:03 UTC, NilsKula commented on src/main/java/io/codelex/flowcontrol/practice/TenBillion.java
> +            if (n >= 10_000_000_000L) {
tagad arī es zinu, ka var pierakstīt izmantojot underscore :smile:

2022-03-07 00:03 UTC, NilsKula commented on src/main/java/io/codelex/flowcontrol/practice/LargestNumber.java
> +        if (num2 > largest) {
pietrūkst papildus `&&`, ja ievadīšu 1, 5, 9 sanāks vien 5

2022-03-08 09:20 UTC, gunahusko commented on src/main/java/io/codelex/flowcontrol/practice/TenBillion.java
> +            if (n >= 10_000_000_000L) {
Nu re, viens otram palīdzam 😄.

2022-03-09 07:31 UTC, gunahusko commented on src/main/java/io/codelex/loops/exercises/Exercise10.java
> +    public static void NumberSquare() {
Paldies, Nil! Metožu nosaukumos camelCase, tiešām ir mana neuzmanības kļūda, auto pilotā, taisot class lielos nosaukumus, nez kāpēc arī metodēs sāku rakstīt. Izlaboju!

2022-03-09 09:01 UTC, gunahusko commented on src/main/java/io/codelex/loops/exercises/Exercise9.java
> +            int dice1 = (int) (Math.random() * range) + min;
Izlaboju. Likās , ka padodot min, max vērtības būs vieglāk noteikt metajamiem kauliņiem no 1 līdz 6, jo Random.nextInt() ģenerē no 0. Bet izdomāju, kā to apiet. Paldies!

2022-03-09 09:01 UTC, gunahusko commented on src/main/java/io/codelex/loops/exercises/Exercise9.java
> +            if (sum == num) isEqualsNum = false;
Ja pēc if ir viena darbība {} var arī nelietot, bet kā ir dzīvē? Ņo lasāmības viedokļa, labāk vienmēr likt? Uzdevumu pārtaisīju, lai var bez šī iztikt. Saskaros ar dažādiem mācību materiāliem, kur kāds liek, kāds nē.

2022-03-09 09:01 UTC, gunahusko commented on src/main/java/io/codelex/loops/exercises/Exercise8.java
> +            for (int j=1; j<=(num-i)*4; j++) {
Paldies, izlaboju.

2022-03-09 09:01 UTC, gunahusko commented on src/main/java/io/codelex/loops/exercises/Exercise7.java
> +        } else if (answer.equals("y")) {
Paldies, izlaboju! Pie reizes, kā Exercise 9 norādīji, es Math.random() nomainīju arī uz Random.nextInt().

2022-03-09 09:01 UTC, gunahusko commented on src/main/java/io/codelex/loops/exercises/Exercise5.java
> +        int dotLength = 30 - firstWord.length() - secondWord.length();
Paldies, izlaboju.

2022-03-09 09:17 UTC, gunahusko commented on src/main/java/io/codelex/flowcontrol/practice/LargestNumber.java
> +        if (num2 > largest) {
Paldies, izlaboju.

2022-03-09 10:00 UTC, NilsKula approved these changes

2022-03-09 10:27 UTC, merged