exceptions
gunahusko/java-home-exercises pull request #8
Opened 2022-03-23 07:44 UTC by gunahusko

2022-03-30 19:42 UTC, NilsKula requested changes

2022-03-30 19:42 UTC, NilsKula commented on src/main/java/io/codelex/exceptions/practice/Exercise2.java
> +public class Exercise2 {
šajā uzdevumā jau domāts ka tev exception rodas C metodē un tad tālāk viņu pa ķēdīti nodod uz augšu līdz sākumam

2022-03-30 19:42 UTC, NilsKula commented on src/main/java/io/codelex/exceptions/practice/Exercise4.java
> +            throw new IllegalArgumentException("Number is negative");
jāuztaisa savs `NonPositiveNumberException` exception ko izmest

2022-03-31 22:37 UTC, gunahusko commented on src/main/java/io/codelex/exceptions/practice/Exercise2.java
> +public class Exercise2 {
Paldies, izlaboju!

2022-03-31 22:37 UTC, gunahusko commented on src/main/java/io/codelex/exceptions/practice/Exercise4.java
> +            throw new IllegalArgumentException("Number is negative");
Paldies, izlaboju!

2022-04-14 09:48 UTC, NilsKula approved these changes
mazā lieta par rethrow

2022-04-14 09:48 UTC, NilsKula commented on src/main/java/io/codelex/exceptions/practice/Exercise2.java
> +public class Exercise2 {
laikam palaidi garām nosacījumu :smile: 
bija domāts ka aiz print `throw e` izmantot, lai noķertu katrā metodē

2022-04-14 11:39 UTC, gunahusko commented on src/main/java/io/codelex/exceptions/practice/Exercise2.java
> +public class Exercise2 {
Paldies, izlabiju.

2022-04-15 18:05 UTC, NilsKula approved these changes

2022-04-16 05:14 UTC, merged