Collections
gunahusko/java-home-exercises pull request #9
Opened 2022-03-25 08:46 UTC by gunahusko

2022-04-10 13:00 UTC, NilsKula requested changes

2022-04-10 13:00 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/Exercise4.java
> +    static Set<String> listOfNames = new HashSet<>();
private and caps

2022-04-10 13:00 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/Histogram.java
> +            if (Integer.parseInt(number) >= 0 && Integer.parseInt(number) <= 9) {
```
if(number < 10)
elese if(number < 20)
utt

2022-04-10 13:00 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneDirectory.java
> +            for (Map.Entry<String, String> info : phoneData.entrySet()) {
`phoneData.get()` ?

2022-04-10 13:00 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneEntry.java
> +    String name;
private

2022-04-12 08:34 UTC, gunahusko commented on src/main/java/io/codelex/collections/practice/Exercise4.java
> +    static Set<String> listOfNames = new HashSet<>();
Paldies, izlaboju!

2022-04-12 08:34 UTC, gunahusko commented on src/main/java/io/codelex/collections/practice/Histogram.java
> +            if (Integer.parseInt(number) >= 0 && Integer.parseInt(number) <= 9) {
Paldies, izlaboju!

2022-04-12 08:34 UTC, gunahusko commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneDirectory.java
> +            for (Map.Entry<String, String> info : phoneData.entrySet()) {
Paldies, izlaboju!

2022-04-12 08:34 UTC, gunahusko commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneEntry.java
> +    String name;
Paldies, izlaboju!

2022-04-16 05:16 UTC, merged